---
title: "T-Bank product case"
output: html_document
date: "2025-08-22"
---
```{r Packages}
install.packages('tidyverse')
install.packages('dplyr')
install.packages('psych')
install.packages('lubridate')
install.packages('viridis')

library(tidyverse)
library(dplyr)
library(psych)
library(lubridate)
library(viridis)

```


```{r Предобработка датасета}
# загружаю датасет и привожу переменные к нужному виду
kicksharing <- read.csv(file = 'kicksharing.csv', 
                   header = TRUE, 
                   sep = ',', 
                   na.strings = c("", "NA"),
                   colClasses = c('character', 'character', 'factor', 'numeric', 'factor', 'factor', 'factor', 'numeric', 'numeric', 'numeric', 'factor', 'numeric', 'character', 'character', 'character', 'factor', 'character', 'numeric', 'numeric', 'numeric'))

# отдельно работаю с типом данных "дата и время"

kicksharing$created_dttm <- as.POSIXct(kicksharing$created_dttm, format = "%Y-%m-%d %H:%M:%OS") 
kicksharing$created_dttm <- as.POSIXct(kicksharing$created_dttm, format = "%Y-%m-%d %H:%M:%OS")
kicksharing$book_start_dttm <- as.POSIXct(kicksharing$book_start_dttm, format = "%Y-%m-%d %H:%M:%OS")
kicksharing$book_end_dttm <- as.POSIXct(kicksharing$book_end_dttm, format = "%Y-%m-%d %H:%M:%OS")
kicksharing$local_book_start_dttm <- as.POSIXct(kicksharing$local_book_start_dttm, format = "%Y-%m-%d %H:%M:%OS")

# перезаписываю датасет без клиентов с аномальным километражом  

iqr <- IQR(kicksharing$distance_km)

lower_bound = quantile(kicksharing$distance_km, 0.25) - 1.5 * iqr
upper_bound = quantile(kicksharing$distance_km, 0.75) + 1.5 * iqr

kicksharing_clean <- kicksharing %>% filter(distance_km <= upper_bound)

# привожу регионы к правильному виду
kicksharing_clean$lvn_state_nm <- gsub("^.*\\МОСКВА\\b.*$", "МОСКВА", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\САНКТ-ПЕТЕРБУРГ\\b.*$", "САНКТ-ПЕТЕРБУРГ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ТАТАРСТАН\\b.*$", "РЕСП ТАТАРСТАН", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\МОСКОВСКАЯ\\b.*$", "МОСКОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\АСТРАХАНСКАЯ\\b.*$", "АСТРАХАНСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ВОЛГОГРАДСКАЯ\\b.*$", "ВОЛГОГРАДСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ГОМЕЛЬСКАЯ\\b.*$", "ГОМЕЛЬСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ИРКУТСКАЯ\\b.*$", "ИРКУТСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\КЕМЕРОВСКАЯ\\b.*$", "КЕМЕРОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ЛЕНИНГРАДСКАЯ\\b.*$", "ЛЕНИНГРАДСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ЧЕЛЯБИНСКАЯ\\b.*$", "ЧЕЛЯБИНСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\АЛТАЙСКИЙ\\b.*$", "АЛТАЙСКИЙ КРАЙ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\КРАСНОДАРСКИЙ\\b.*$", "КРАСНОДАРСКИЙ КРАЙ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\КРАСНОЯРСКИЙ\\b.*$", "КРАСНОЯРСКИЙ КРАЙ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ПЕРМСКИЙ\\b.*$", "ПЕРМСКИЙ КРАЙ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ХАБАРОВСКИЙ\\b.*$", "ХАБАРОВСКИЙ КРАЙ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ПРИМОРСКИЙ\\b.*$", "ПРИМОРСКИЙ КРАЙ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\КАМЧАТСКИЙ\\b.*$", "КАМЧАТСКИЙ КРАЙ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\СТАВРОПОЛЬСКИЙ\\b.*$", "СТАВРОПОЛЬСКИЙ КРАЙ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ХАНТЫ-МАНСИЙСКИЙ\\b.*$", "ХАНТЫ-МАНСИЙСКИЙ АО", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ЧУВАШИЯ\\b.*$", "РЕСП ЧУВАШИЯ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ЯКУТИЯ\\b.*$", "РЕСП САХА/ЯКУТИЯ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\НОВОСИБИРСКАЯ\\b.*$", "НОВОСИБИРСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ЯРОСЛАВСКАЯ\\b.*$", "ЯРОСЛАВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\МУРМАНСКАЯ\\b.*$", "МУРМАНСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ЕВРЕЙСКАЯ\\b.*$", "ЕВРЕЙСКАЯ АОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\КУРГАНСКАЯ\\b.*$", "КУРГАНСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\АМУРСКАЯ\\b.*$", "АМУРСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\БЕЛГОРОДСКАЯ\\b.*$", "БЕЛГОРОДСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ТОМСКАЯ\\b.*$", "ТОМСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ТВЕРСКАЯ\\b.*$", "ТВЕРСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ТЮМЕНСКАЯ\\b.*$", "ТЮМЕНСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ИВАНОВСКАЯ\\b.*$", "ИВАНОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\МОСККОВСКАЯ\\b.*$", "МОСКОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\НОВГОРОДСКАЯ\\b.*$", "НОВГОРОДСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\КАЛИНИНГРАДСКАЯ\\b.*$", "КАЛИНИНГРАДСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ЛИПЕЦКАЯ\\b.*$", "ЛИПЕЦКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\НИЖЕГОРОДСКАЯ\\b.*$", "НИЖЕГОРОДСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ЛЕНЕНГРАДСКАЯ\\b.*$", "ЛЕНИГРАДСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\САМАРСКАЯ\\b.*$", "САМАРСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\САХАЛИНСКАЯ\\b.*$", "САХАЛИНСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\СВЕРДЛОВСКАЯ\\b.*$", "СВЕРДЛОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\САМАРА\\b.*$", "САМАРСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\КИРОВСКАЯ\\b.*$", "КИРОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\КУРСКАЯ\\b.*$", "КУРСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ОРЛОВСКАЯ\\b.*$", "ОРЛОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\РЯЗАНСКАЯ\\b.*$", "РЯЗАНСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\АРХАНГЕЛЬСКАЯ\\b.*$", "АРХАНГЕЛЬСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\КАЛУЖСКАЯ\\b.*$", "КАЛУЖСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ПЕНЗЕНСКАЯ\\b.*$", "ПЕНЗЕНСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\УЛЬЯНОВСКАЯ\\b.*$", "УЛЬЯНОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\РОСТОВСКАЯ\\b.*$", "РОСТОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\САРАТОВСКАЯ\\b.*$", "САРАТОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ВЛАДИМИРСКАЯ\\b.*$", "ВЛАДИМИРСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ВОРОНЕЖСКАЯ\\b.*$", "ВОРОНЕЖСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\КОСТРОМСКАЯ\\b.*$", "КОСТРОМСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ПСКОВСКАЯ\\b.*$", "ПСКОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ТАМБОВСКАЯ\\b.*$", "ТАМБОВСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ОРЕНБУРГСКАЯ\\b.*$", "ОРЕНБУРГСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ВОЛОГОДСКАЯ\\b.*$", "ВОЛОГОДСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\СМОЛЕНСКАЯ\\b.*$", "СМОЛЕНСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ИНГУШЕТИЯ\\b.*$", "РЕСП ИНГУШЕТИЯ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ДОНЕЦКАЯ\\b.*$", "РЕСП ДОНЕЦКАЯ НАРОДНАЯ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\БАШКОРТОСТАН\\b.*$", "РЕСП БАШКОРТОСТАН", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\БРЕСТСКАЯ\\b.*$", "БРЕСТСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ЯМАЛО-НЕНЕЦКИЙ\\b.*$", "ЯМАЛО-НЕНЕЦКИЙ АО", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ЛЕНИГРАДСКАЯ\\b.*$", "ЛЕНИГРАДСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ЛНР\\b.*$", "РЕСП ЛУГАСКАЯ НАРОДНАЯ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\НЕНЕЦКИЙ\\b.*$", "ЯМАЛО-НЕНЕЦКИЙ АО", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\МАРИЙ\\b.*$", "РЕСП МАРИЙ ЭЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\ТУЛЬСКАЯ\\b.*$", "ТУЛЬСКАЯ ОБЛ", kicksharing_clean$lvn_state_nm)
kicksharing_clean$lvn_state_nm <- gsub("^.*\\УДМУРТСКАЯ\\b.*$", "РЕСП УДМУРТИЯ", kicksharing_clean$lvn_state_nm)

# меняю вид переменной на фактор
kicksharing_clean$lvn_state_nm <- as.factor(kicksharing_clean$lvn_state_nm)

summary(kicksharing_clean$lvn_state_nm)

```


```{r Структура датасета}

# описываю датасет

summary(kicksharing_clean)

describe(kicksharing_clean)

# считаю пропущенные значения
na_summary <- kicksharing_clean %>%
  summarise(across(everything(), ~sum(is.na(.)))) %>%
  pivot_longer(everything(), names_to = "variable", values_to = "NA_count") %>%
  arrange(desc(NA_count))

# считаю число уникальный клиентов
n_distinct(kicksharing_clean$party_rk)

```


```{r Возрастное распределение клиентов}

iqr_age <- IQR(kicksharing_clean$age)

lower_bound_age = quantile(kicksharing_clean$age, 0.25) - 1.5 * iqr_age
upper_bound_age = quantile(kicksharing_clean$age, 0.75) + 1.5 * iqr_age

kicksharing_clean %>% 
  select(age) %>%
  filter(age <= upper_bound_age & age >= lower_bound_age) %>%
  boxplot(main = 'Возрастное распределение клиентов (без выбросов)', 
       ylab = 'Возраст',
       caption = 'Источник: датасет Т-Банка о поездках на самокатах, 2024',
       col = '#FFDD2D')

```


```{r Длительность поездки среди мужчин и женщин}

# создаю новую переменную "длительность поездки" 

kicksharing_clean <- kicksharing_clean %>%
  mutate(book_duration = difftime(book_end_dttm, book_start_dttm, units = "mins"))

kicksharing_clean$book_duration <- as.numeric(kicksharing_clean$book_duration)

# определяю численные значения в новой переменной для учета выбросов

iqr_dur <- IQR(kicksharing_clean$book_duration)

lower_bound_dur = quantile(kicksharing_clean$book_duration, 0.25) - 1.5 * iqr_dur
upper_bound_dur = quantile(kicksharing_clean$book_duration, 0.75) + 1.5 * iqr_dur

summary(kicksharing_clean$book_duration)

# визуализирую средние значения длительности поездок для мужчин и женщин

kicksharing_clean %>%
  select(gender_cd, book_duration) %>%
  filter(book_duration <= upper_bound_dur 
         & book_duration >= lower_bound_dur
         & is.na(gender_cd) == FALSE) %>%
  group_by(gender_cd) %>% 
  summarise(average_duration = mean(book_duration)) %>% 
  ggplot(aes(gender_cd, average_duration))+
  geom_col(fill = '#FFDD2D')+
  theme_light()+
  labs(title = "Среднее время поездки среди женщин и мужчин", y = 'Среднее время поездки', x = 'Пол клиента')
```


```{r Длина поездки по месяцам}

summary(kicksharing_clean$distance_km)

kicksharing_clean %>%
  select(month, distance_km) %>%
  filter(is.na(month) == FALSE) %>%
  group_by(month) %>% 
  summarise(average_distance = mean(distance_km)) %>% 
  ggplot(aes(month, average_distance))+
  geom_col(fill = '#FFDD2D')+
  theme_light()+
  labs(title = "Средняя длина поездки по месяцам", 
       y = 'Средняя длина поездки', 
       x = 'Месяц')

```


```{r Половое распределение клиентов в 10 самых активных регионах}

# сохраняю датафрейм с нужными данными для последующей визуализации

top_regions_gender <- kicksharing_clean %>%
  select(lvn_state_nm, 
         distance_km, 
         book_duration, 
         party_rk, 
         gender_cd) %>%
  group_by(lvn_state_nm) %>%
  summarise(clients_amt = n_distinct(party_rk), 
            male_clients = n_distinct(party_rk[gender_cd == "M"]),
            female_clients = n_distinct(party_rk[gender_cd == "F"])) %>%
  arrange(desc(clients_amt)) %>%
  slice_head(n = 10) %>%
  mutate(top_regions = fct_reorder(lvn_state_nm, clients_amt, .desc = TRUE)) %>%
  pivot_longer(
    cols = c(male_clients, female_clients),
    names_to = "gender",
    values_to = "count") %>%
  mutate(gender = case_when(
    gender == "male_clients" ~ "Мужчины",
    gender == "female_clients" ~ "Женщины")) 

#　абсолютные значения для полового распределения

top_regions_gender %>%
ggplot(aes(top_regions, 
             count, fill = gender))+
  geom_col(position = 'dodge')+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.6))+
  scale_fill_manual(values = c("Мужчины" = "#FFDD2D", "Женщины" = "#000000"))+
  labs(title = "Топ-10 регионов по количеству клиентов", 
       caption = "Источник: датасет Т-Банка о поездках на самокатах, 2024", 
       x = 'Регионы', 
       y = 'Количество уникальных клиентов', 
       fill = 'Пол клиентов')

# относительные значения для полового распределения

top_regions_gender %>%
  ggplot(aes(top_regions, 
             count, fill = gender))+
  geom_col(position = 'fill')+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.6))+
  scale_fill_manual(values = c("Мужчины" = "#FFDD2D", "Женщины" = "#000000"))+
  labs(title = "Топ-10 регионов по количеству клиентов", 
       caption = "Источник: датасет Т-Банка о поездках на самокатах, 2024", 
       x = 'Регионы', 
       y = 'Количество уникальных клиентов', 
       fill = 'Пол клиентов')
```



```{r Самые активные часы заказов кикшеринга}

kicksharing_clean <- kicksharing_clean %>%
  mutate(
    timezone_int = as.integer(gsub("0", "", as.character(book_time_zone_cd))),
    hour_int = lubridate::hour(book_start_dttm),
    adjusted_hour = as.factor((hour_int + (timezone_int - 3)) %% 24))

kicksharing_clean %>%
  select(adjusted_hour) %>%
  group_by(adjusted_hour) %>%
  summarise(freq = n()) %>%
  ggplot(aes(adjusted_hour, freq))+
  geom_col(fill = '#FFDD2D')+
  labs(
    title = 'Наиболее активные часы заказов',
    x = 'Часы начала поездки с поправкой на часовые пояса',
    y = 'Частота',
    caption = 'Источник: датасет Т-Банка о поездках на самокатах, 2024',
    subtitle = 'n = 370254'
    )

```

```{r Самые активные часы заказов кикшеринга (тепловая карта)}

kicksharing_clean %>%
  select(adjusted_hour) %>%
  group_by(adjusted_hour) %>%
  summarise(freq = n(), .groups = 'drop') %>%
  ggplot(aes(x = adjusted_hour, y = 1, fill = freq)) +
  geom_tile(color = "white", linewidth = 0.5) +
  scale_fill_gradientn(
    colors = c("black", "#333333", "#666666", "#999999", 
               "#CCCC00", "#FFFF00", "#FFFF33"),
    name = "Количество\nпоездок"
  ) +
  scale_x_discrete(breaks = 0:23) +
  labs(
    title = "Самые активные часы для заказов кикшеринга",
    subtitle = "Общая статистика за все месяцы",
    x = "Часы начала поездки (с поправкой на часовые пояса)",
    y = NULL,
    caption = "Источник: датасет Т-Банка о поездках на самокатах, 2024")+
  theme_minimal()+
  theme(
    axis.text.y = element_blank(),
    axis.text.x = element_text(hjust = 1, size = 10),
    panel.grid = element_blank(),
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5),
    plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(b = 15)),
    legend.position = "right",
    legend.key.height = unit(1.5, "cm"))

```


```{r T-Tест для основной гипотезы}
women <- kicksharing_clean %>%
  select(gender_cd, book_duration) %>%
  filter(gender_cd == 'F' 
         & book_duration <= upper_bound_dur 
         & book_duration >= lower_bound_dur)

men <- kicksharing_clean %>%
  select(gender_cd, book_duration) %>%
  filter(gender_cd == 'M' 
         & book_duration <= upper_bound_dur 
         & book_duration >= lower_bound_dur) 

t.test(women$book_duration, men$book_duration, alternative = "greater", var.equal = FALSE)

t_test_welch <- t.test(book_duration ~ gender_cd, 
                      data = kicksharing_clean,
                      alternative = "greater")
print(t_test_welch)
```

```{r Miscellaneous}
vignette('dplyr') # можно посоветовать первашам

install.packages("rmarkdown")
install.packages("reticulate")

library(reticulate)
# Конвертация в R
rmarkdown::convert("T-Bank product case.Rmd", to = "ipynb")
```
